"""Add field clicks to URL, created_at to Base

Revision ID: 9cac1cdd2f7e
Revises: 2d2719fc098b
Create Date: 2026-08-15 23:25:20.359349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cac1cdd2f7e'
down_revision: Union[str, Sequence[str], None] = '2d2719fc098b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('token', sa.String(), nullable=False))
    op.add_column('urls', sa.Column('original_url', sa.String(), nullable=False))
    op.add_column('urls', sa.Column('clicks', sa.Integer(), nullable=False))
    op.add_column('urls', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('urls', 'shorted')
    op.drop_column('urls', 'original')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('original', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('urls', sa.Column('shorted', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('urls', 'created_at')
    op.drop_column('urls', 'clicks')
    op.drop_column('urls', 'original_url')
    op.drop_column('urls', 'token')
    # ### end Alembic commands ###
